export const ADD_CATEGORY = 'ADD_CATEGORY';
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_SCORE = 'UPDATE_SCORE';
export const ADD_TO_LEADERBOARD = 'ADD_TO_LEADERBOARD';
export const SAVE_TO_STORAGE = 'SAVE_TO_STORAGE';
export const GET_FROM_STORAGE = 'GET_FROM_STORAGE';